language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "haloislet"
  - git config user.email "haloislet@gmail.com"
  - git add .
  - git commit -m "update blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog
env:
 global:
   - GH_REF: github.com/haloislet/haloislet.github.io.git

